routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TaskController;
use App\Http\Middleware\CheckUser;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/auth', [HomeController::class, 'auth'])->name('auth');

Route::group([
    'as' => 'tasks.',
    'prefix' => 'tasks',
], function() {
    Route::get('/', [TaskController::class, 'index'])->name('index');
    Route::get('/create', [TaskController::class, 'create'])->name('create');
    Route::post('/', [TaskController::class, 'store'])->name('store');
    Route::get('/{task}', [TaskController::class, 'show'])->name('show');
    Route::get('/{task}/edit', [TaskController::class, 'edit'])->name('edit');
    Route::put('/{task}', [TaskController::class, 'update'])->name('update');
    Route::delete('/{task}', [TaskController::class, 'destroy'])->name('destroy');
});

















Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Task.php
<?php

namespace App\Models;

use App\Jobs\SendTaskToEmailJob;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description', 'category_id', 'image'];

    protected static function booted()
    {
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('deadline');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Events\UpdateTask;
use App\Http\Requests\StoreTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Jobs\SendTaskToEmailJob;
use App\Mail\TaskCreated;
use App\Mail\TaskUpdated;
use App\Models\Category;
use App\Models\Task;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Mail;
use Illuminate\View\View;
use Illuminate\Support\Facades\Gate;

class TaskController extends Controller
{

    public function __construct()
    {
        $this->middleware('check.user');
    }
    public function index(): View
    {
//        $this->authorize('viewAny', Task::class);

        $tasks = Task::query()->latest()->get();

        return view('tasks.index', ['tasks' => $tasks]);
    }

    public function create(): View
    {
        $categories = Category::all();
        $users = User::all();

        return view('tasks.create', compact('categories', 'users'));
    }

    /**
     * @param StoreTaskRequest $request
     * @return RedirectResponse
     */
    public function store(StoreTaskRequest $request): \Illuminate\Http\RedirectResponse
    {
        $validated = $request->validated();
        $taskData = Arr::except($validated, ['users', 'deadline']);
        if ($request->file('image') !== null) {
            $taskData['image'] = $request->file('image')->store('images');
        }
        $usersData = Arr::get($validated, 'users', []);
        $deadline = Arr::get($validated, 'deadline', null);
        $task = Task::create($taskData);
        $task->users()->attach($usersData, ['deadline' => $deadline]);

        SendTaskToEmailJob::dispatch($task, $request->user());

        return redirect()->route('tasks.index');
    }

    public function show(Task $task): View
    {
        $user = request()->user();
        if ($user && $user->can('view', $task)) {
            return view('tasks.show', ['task' => $task]);
        }
        abort(403);

//        $this->authorize('view', $task);
//
//        return view('tasks.show', ['task' => $task]);

    }

    public function edit(Task $task)
    {
        Gate::authorize('update-task', $task);
        $categories = Category::all();
        $users = User::all();
        $selectedUsers = $task->users()->get(['id'])->pluck('id')->toArray();
        $date = $task->users()->first()->pivot->deadline;
        $deadline = Carbon::parse($date)->format('Y-m-d');

        return view('tasks.edit', compact('task', 'categories', 'users', 'selectedUsers', 'deadline'));
    }

    public function update(UpdateTaskRequest $request, Task $task)
    {
        $validated = $request->validated();
        $taskData = Arr::except($validated, ['users', 'deadline']);
        $users = Arr::get($validated, 'users', []);
        $deadline = Arr::get($validated, 'deadline', null);
        $task->update($validated);
        $task->users()->syncWithPivotValues($users, ['deadline' => $deadline]);
        event(new UpdateTask($task));

        return redirect()->route('tasks.index');
    }

    public function destroy(Task $task)
    {
        $task->delete();
        return redirect()->route('tasks.index');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.main')

@section('title', 'Создать задачу')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="POST" action="{{ route('tasks.store') }}" enctype="multipart/form-data">
        @csrf
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Ім'я</span>
            <input
                type="text"
                class="form-control"
                name="name"
                aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default"
                placeholder="Введіть ім'я"
                value="{{ old('name') }}"
                class="@error('name') is-invalid @enderror"
            >
        </div>
        @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Опис</span>
            <input
                type="text"
                class="form-control"
                name="description"
                aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default"
                placeholder="Введіть опис"
                value="{{ old('description') }}"
                class="@error('description') is-invalid @enderror"
            >
        </div>
        @error('description')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="input-group mb-3">
            <label class="input-group-text" for="inputGroupSelectCategory">Категорія</label>
            <select class="form-select" name="category_id" id="inputGroupSelect01">
                <option selected>Оберіть категорію...</option>
                @foreach($categories as $category)
                    <option value="{{ $category->id }}" {{ old('category_id') == $category->id ? 'selected' : ''}}>{{ $category->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="input-group mb-3">
            <label class="input-group-text" for="inputGroupSelectCategory">Виконавці</label>
            <select class="form-select" multiple name="users[]" id="inputGroupSelect02">
                <option disabled>Оберіть виконавцев...</option>
                @foreach($users as $user)
                    <option value="{{ $user->id }}" {{ in_array( $user->id, old('users', []))  ? 'selected' : ''}}>{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        @error('users')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror

        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Строк</span>
            <input
                type="date"
                class="form-control"
                name="deadline"
                aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default"
                value="{{ old('deadline') }}"
                class="@error('deadline') is-invalid @enderror"
            >
        </div>
        @error('deadline')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
            <label for="image" class="form-label">Зображення</label>
            <input class="form-control" type="file" id="image" name="image">
        </div>
        @error('image')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror

        <button type="submit">Send</button>
    </form>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.main')

@section('title', 'Создать задачу')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="POST" action="{{ route('tasks.update', ['task' => $task->id]) }}" enctype="multipart/form-data">
        @method('PUT')
        @csrf
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Ім'я</span>
            <input
                type="text"
                class="form-control"
                aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default"
                name="name"
                placeholder="Введіть ім'я"
                class="@error('name') is-invalid @enderror"
                value="{{old('name', $task->name)}}"
            >
        </div>
        @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Опис</span>
            <input
                type="text"
                name="description"
                class="form-control"
                aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default"
                placeholder="Введіть опис"
                class="@error('description') is-invalid @enderror"
                value="{{ old('description', $task->description) }}"
            >
        </div>
        @error('description')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="input-group mb-3">
            <label class="input-group-text" for="inputGroupSelect01">Options</label>
            <select
                class="form-select"
                id="inputGroupSelect01"
                name="category_id"
                class="@error('category_id')
                 is-invalid @enderror"
            >
                <option selected>Оберіть категорію</option>
                @foreach($categories as $category)
                    <option
                        value="{{ $category->id }}"
                        {{ old('category_id', $task->category_id) ==  $category->id ? 'selected' : '' }}
                    >
                        {{ $category->name }}
                    </option>
                @endforeach
            </select>
        </div>
        @error('category_id')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror

        <div class="input-group mb-3">
            <label class="input-group-text" for="inputGroupSelectCategory">Виконавці</label>
            <select class="form-select" multiple name="users[]" id="inputGroupSelect02">
                <option disabled>Оберіть виконавцев...</option>
                @foreach($users as $user)
                    <option value="{{ $user->id }}" {{ in_array( $user->id, old('users', $selectedUsers))  ? 'selected' : ''}}>{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        @error('users')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror

        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Строк</span>
            <input
                type="date"
                class="form-control"
                name="deadline"
                aria-label="Sizing example input"
                aria-describedby="inputGroup-sizing-default"
                value="{{ old('deadline', $deadline) }}"
                class="@error('deadline') is-invalid @enderror"
            >
        </div>
        @error('deadline')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
            <label for="image" class="form-label">Зображення</label>
            <input class="form-control" type="file" id="image" name="image">
        </div>
        @error('image')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror

        <button type="submit">Send</button>
    </form>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.main')

@section('title', 'Список задач')

@section('content')
    <h1 class="title text-center">Список задач</h1>
    <div class="container">
        <div class="row row-cols-3">
            @foreach($tasks as $task)
                <div class="col">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{ $task->name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ $task->category->name }}</h6>
                            <p class="card-text">{{ $task->description }}</p>
                            <a href="{{ route("tasks.edit", ['task' => $task->id]) }}" class="card-link">Редактировать</a>
                            <a href="{{ route("tasks.show", ['task' => $task->id]) }}" class="card-link">Перейти</a>
                            <form action="{{ route("tasks.destroy", ['task' => $task->id]) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.main')

@section('title', 'Список задач')

@section('content')
    <h1 class="title">Задача - {{ $task->name }}</h1>
    <img src="{{ asset("storage/$task->image") }}" alt="blabla">
    <div class="container">
        <div class="row row-cols-3">
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ $task->name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ $task->category->name }}</h6>
                        <p class="card-text">{{ $task->description }}</p>
                        <a href="{{ route("tasks.edit", ['task' => $task->id]) }}" class="card-link">Редактировать</a>
                        <a href="#" class="card-link">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection